# Generated by Django 6.0.3 on 2026-04-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="Ім'я та прізвище")),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
            ],
            options={
                'verbose_name': 'Актор',
                'verbose_name_plural': 'Актори',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва жанру')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва фільму')),
                ('description', models.TextField(verbose_name='Опис')),
                ('release_year', models.PositiveIntegerField(verbose_name='Рік випуску')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер')),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.actor', verbose_name='Актори')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre', verbose_name='Жанри')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
            },
        ),
    ]
